import React from 'react';
import Head from 'next/head';
import { css } from '@emotion/react';
import { animalsDatabase } from '../util/database';
import Link from 'next/link';

const animalsStyles = css`
  border-radius: 5px;
  padding: 20px 30px;
  & + & {
    margin-top: 10px;
  }
  display: flex;
  flex-wrap: wrap;
  flex-direction: row;
  justify-content: space-evenly;
`;
const productStyle = css`
  border: 1px solid #ddd;
  border-radius: 10px;
  padding: 20px;
  width: 20%;
`;
const products = css`
  width: 70%;
  margin: auto;
  padding: 100px 0;

  h1 {
    font-size: 3rem;
    font-weight: 600;
  }
`;
export default function Animals(props) {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css"
        />
      </Head>
      <section css={products}>
        <h1>Products</h1>
        {/* <article>
          <div>
            <span>Category:</span>
            <input type="radio" name="category" id="all" value="all" checked />
            <label htmlFor="all">All</label>
            <input type="radio" name="category" id="men" value="Men" />
            <label htmlFor="men">Men</label>
            <input type="radio" name="category" id="women" value="Women" />
            <label htmlFor="women">Women</label>
          </div>
        </article> */}
      </section>
      <div css={animalsStyles}>
        {props.animals.map((animal) => {
          return (
            <div css={productStyle} key={`animal-${animal.id}`}>
              {/* <div>Name:{animal.name}</div>
              <div>Type:{animal.price}</div>
              <div>
                <img key={animal.id} src={animal.image} alt="" />
              </div> */}
              <Link href={`/animals/${animal.id}`}>
                <a>
                  <img src={animal.image} alt="" width="300px" height="280px" />
                  <h3>{animal.name} </h3>
                  <p>{animal.price}</p>
                  <p>{animal.decription}</p>
                </a>
              </Link>
            </div>
          );
        })}
      </div>
    </div>
  );
}

export function getServerSideProps() {
  return {
    props: {
      animals: animalsDatabase,
    },
  };
}
